apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: goormthon-5

resources:
  - backend.yaml
  # - ingress.yaml # API 호출 방식이 Client-Side인 경우 주석 해제

configMapGenerator:
  - name: backend-config
    files:
      - config.json=config/backend-config.json

generatorOptions:
  disableNameSuffixHash: true